name: Gitleaks Security Scan

on:
  pull_request:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # Run daily at 4 AM UTC

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  scan:
    name: Scan for secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for comprehensive scan

      - name: Run Gitleaks
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: true
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_ENABLE_SUMMARY: true

      - name: Upload SARIF report
        if: failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: gitleaks

      - name: Security scan completed
        if: success()
        run: |
          echo "✅ No secrets detected in the repository!"
          echo "Scanned full git history for sensitive information."
